volumes:
  calorie-tracker-data:

services:
  calorie-tracker:
    build: .
    container_name: calorie-tracker
    ports:
      - 3001:3000
    restart: unless-stopped

  calorie-tracker-db:
    image: postgres:16.1
    container_name: calorie-tracker-db
    environment:
      - POSTGRES_DB=database
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - calorie-tracker-data:/var/lib/postgresql/data
    restart: unless-stopped
